### ISSUE TITLE
ErrFieldResponse

### ISSUE THREAD

**Issue by cheebo** [nori-io/auth#5]
https://github.com/nori-io/auth/blob/9c483d46c34111c50aa6c77028b4e888960b5e76/service/decode.go#L31

If function Validate() returns not nil error and this error has type of ErrFieldResp, then we must return this error, otherwise return custom ErrFieldResp with ErrMessage = err.String():

```go
if err := body.Validate(); err != nil {
  switch err.(type) {
  case rest.ErrFieldResp:
    return body, err
  ...
  // если у нас не ErrFieldResp, тогда default
  default: 
    return body, rest.ErrFieldResp{
      Meta: rest.ErrFieldRespMeta{
          ErrMessage: err.String(),
        },
      }
}
```

**Comment by bruteforce1414** [comment]
Not actual
